Repository J1P3ter/Astraphe, pull requests merged in 2024-10, with the labels that each got.

#14 Feat common
  common/src/main/java/com/j1p3ter/common/config/CacheConfig.java
  common/src/main/java/com/j1p3ter/common/config/CorsConfigurer.java
  common/src/main/java/com/j1p3ter/common/exception/ApiException.java
  common/src/main/java/com/j1p3ter/common/exception/ApiExceptionHandler.java
  common/src/main/java/com/j1p3ter/common/response/ApiResponse.java
Labels: enhancement

#30 feat_order_#5
  build.gradle
  order-server/.gitignore
  order-server/build.gradle
  order-server/gradle/wrapper/gradle-wrapper.jar
  order-server/gradle/wrapper/gradle-wrapper.properties
  order-server/gradlew
  order-server/gradlew.bat
  order-server/src/main/java/com/j1p3ter/orderserver/OrderServerApplication.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/Order.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/OrderDetail.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/OrderRepository.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/OrderState.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/PaymentMethod.java
  order-server/src/main/resources/application-dev.yml
  order-server/src/main/resources/application-prod.yml
  order-server/src/main/resources/application.yml
  order-server/src/test/java/com/j1p3ter/orderserver/OrderServerApplicationTests.java
  settings.gradle
Labels: good first issue

#33 fix_order_#5
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/Order.java
  order-server/src/main/java/com/j1p3ter/orderserver/domain/order/OrderDetail.java
Labels: fix

#34 Reduce Stock Kafka 로직 구현
  common/src/main/java/com/j1p3ter/common/auditing/AuditorAwareImpl.java
  product-server/build.gradle
  product-server/src/main/java/com/j1p3ter/productserver/application/ProductService.java
  product-server/src/main/java/com/j1p3ter/productserver/domain/product/Product.java
  product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/EventSerializer.java
  product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/event/ReduceStockEvent.java
  product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/handler/KafkaErrorHandler.java
  product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/messaging/ProductEventConsumer.java
  product-server/src/main/java/com/j1p3ter/productserver/presentation/KafkaTestController.java
  product-server/src/main/java/com/j1p3ter/productserver/presentation/ProductController.java
  product-server/src/main/resources/application-dev.yaml
  product-server/src/main/resources/application-prod.yaml
  product-server/src/main/resources/application.yaml
Labels: enhancement
